create table policies (
  id bigint generated by default as identity primary key,
  type varchar(20) not null,
  status varchar(20) not null,
  effective_from date not null,
  effective_to date not null,
  initial_duration_months integer not null,
  monthly_rent numeric(19, 2) not null,
  premium numeric(19, 2) not null,
  policyholder_name varchar(160),
  beneficiary_name varchar(160),
  version bigint not null default 0,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  constraint ck_policies_type check (type in ('INDIVIDUAL', 'COLECTIVA')),
  constraint ck_policies_status check (status in ('ACTIVA', 'RENOVADA', 'CANCELADA')),
  constraint ck_policies_dates check (effective_to >= effective_from),
  constraint ck_policies_duration check (initial_duration_months > 0),
  constraint ck_policies_monthly_rent check (monthly_rent > 0),
  constraint ck_policies_premium check (premium > 0)
);

create table risks (
  id bigint generated by default as identity primary key,
  policy_id bigint not null references policies(id),
  property_address varchar(240) not null,
  tenant_name varchar(160) not null,
  status varchar(20) not null,
  version bigint not null default 0,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  constraint ck_risks_status check (status in ('ACTIVO', 'CANCELADO'))
);

create index idx_policies_type_status on policies(type, status);
create index idx_risks_policy_id on risks(policy_id);

create table core_outbox_events (
  id uuid primary key,
  policy_id bigint not null references policies(id),
  event_type varchar(40) not null,
  status varchar(20) not null,
  attempts integer not null default 0,
  next_attempt_at timestamp with time zone not null,
  last_error varchar(1000),
  created_at timestamp with time zone not null,
  sent_at timestamp with time zone,
  version bigint not null default 0,
  constraint ck_core_outbox_status check (status in ('PENDING', 'SENT', 'FAILED')),
  constraint ck_core_outbox_attempts check (attempts >= 0)
);

create index idx_core_outbox_dispatch
  on core_outbox_events(status, next_attempt_at, created_at);

